
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: grafana
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/component: grafana
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/component: grafana
      annotations: null
    spec:
      containers:
      - image: grafana/grafana
        name: grafana-core
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
        volumeMounts:
        - name: dashboard-provisioning
          mountPath: /etc/grafana/provisioning/dashboards
        - name: ozone-dashboard
          mountPath: /etc/ozone-dashboard
        - name: prometheus-datasource-provisioning
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
          subPath: prometheus.yaml
        - name: loki-datasource-provisioning
          mountPath: /etc/grafana/provisioning/datasources/loki.yaml
          subPath: loki.yaml
        - name: kubedashboard
          mountPath: /etc/kubedashboard
        - name: nodeexporter-grafana-dashboard
          mountPath: /etc/dashboards/cluster.json
          subPath: cluster.json
        - name: nodeexporter-grafana-dashboard
          mountPath: /etc/dashboards/hosts.json
          subPath: hosts.json
      volumes:
      - name: dashboard-provisioning
        configMap:
          name: grafana-dashboards
      - name: ozone-dashboard
        configMap:
          name: ozone-dashboard
      - name: prometheus-datasource-provisioning
        configMap:
          name: prometheus-grafana-datasource
      - name: loki-datasource-provisioning
        configMap:
          name: loki-grafana-datasource
      - name: kubedashboard
        configMap:
          name: kubedashboard
      - name: nodeexporter-grafana-dashboard
        configMap:
          name: nodeexporter-grafana-dashboard
